# Based on: https://github.com/foresterre/cargo-msrv/blob/main/.github/workflows/msrv.yml

name: MSRV
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  msrv:
    name: Verify minimum supported Rust version

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-msrv
        run: cargo binstall --no-confirm cargo-msrv

      - name: Run cargo-msrv
        run: cargo msrv verify --output-format json

      - name: Run cargo-msrv on verification failure
        if: ${{ failure() }}
        run: cargo msrv find --output-format json
